# Assignment 1

In [14]:
import numpy as np
from numpy.linalg import inv

# Please replace "MatricNumber" with your actual matric number here and in the filename
def A1_A0200725U(X, y):
    """
    Input type
    :X type: numpy.ndarray
    :y type: numpy.ndarray

    Return type
    :w type: numpy.ndarray
    :XT type: numpy.ndarray
    :InvXTX type: numpy.ndarray
   
    """
    # your code goes here
    XT = X.T
    InvXTX = inv(XT @ X)
    w = InvXTX @ X.T @ y

    # return in this order
    return w, XT, InvXTX

X = np.array([[1,2],[4,3],[5,6],[4,8],[9,10]])
y = np.array([[-1],[0],[1],[0],[0]])
A1_A0200725U(X, y)

(array([[ 0.0916626 ],
        [-0.05265724]]),
 array([[ 1,  4,  5,  4,  9],
        [ 2,  3,  6,  8, 10]]),
 array([[ 0.10385178, -0.08093613],
        [-0.08093613,  0.06777182]]))